### PR TITLE
EntityFinder - fix usages of Reflection library retrieve only Entity classes in the configured packages

### PR DESCRIPTION
**Pull request by fabio-bonfante**
Using this plugin in my projects I've found that the packages configuration doesn't have effects, and all the Entity are found creating the ddl for all of them.

Looking at the code and at the Reflection library documentation seems that a `filterInputsBy(new FilterBuilder().includePackage(packageName)));` is needed to return the classes in a given package.

Added a unit-test inside the plugin-core (not covering all the code, but I've no experience in actual testing/developing maven plugins)... hope it helps.

### CODE REVIEW

**Comment by fabio-bonfante** [comment]
Hello @jpdigital can you please check this PR? 
Thanks in advance.
Fabio

**Comment by jpdigital** [comment]
Hello fabio-bonfante,

sorry for the delay. Unfortunately, the final phase of my PhD has taken a lot of time in the last months. I merged your changes not into the master/main branch because I recently migrated all (integration) tests to use the maven-invoker-plugin, which is the officially supported way for testing Maven plugins.  I will port you Unit-Test to such an integration test. Also, I'm not completely sure if the filter works in all cases. Therefore I created a new branch for improving the EntityFinder, and merged your changes into that branch. 

There also some other issues I would like to address before I release the next version. But I hope to release the new version by the end of this month.

Best

Jens

**Comment by jpdigital** [comment]
There are now some conflicts. Could you please resolve them first? After the conflicts are resolved I will merge you changes.

**Comment by jpdigital** [comment]
I've integrated your suggested solution now, but in a slightly different way. Also created a test for the solution using the maven-invoker-plugin instead of a Unit test.

**Comment by fabio-bonfante** [comment]
Sorry also for me.... life, work, and new baby happens ;-)
Didn't had time to try your latest change, but thanks for your work!

**Pull request closed without merging**
